### ISSUE TITLE
Implement the view count

### ISSUE THREAD

**Issue by TKone7** [TKone7/lightread#14]
Every time an article is visited the view should be logged so to show the author a statistics of how much his content is being viewed.
## To consider
- Do we count all requests
- or only once per IP / user in a specific time range

**Comment by RomanBoegli** [comment]
That's a good and interesting question. Let's assume we know the following information:

- requester's user-id (because he is logged in) or IP address (less concise but better than nothing)
- estimated time to read ([ETR](https://github.com/michael-lynch/reading-time))
- time spend on the article page

When a show the article page to a requester, we count a new view.
When the same requester requests the same article within a time span which is shorter than (say) 2x the article's ETR, we ignore the view.
Requests after the 2x ETR duration will increase the counter again.

We could refine this strategy with the time spend (TS) on the article page. For instance, if an article with an ETR of 10 minutes is shown 7 minutes to a requester, then we count 0.7 views. However, a single view measurement won't exceed 1.0 (e.g. requester leaves the article open for hours).

What do you think?

**Comment by RomanBoegli** [comment]
Alternatively, we could also distinguish between *views* and *reads*. *Views* would then simply be the number of article requests while *reads* is the summation of the TS/ETR values.

**Comment by RomanBoegli** [comment]
I prepared our database accordingly...

**Comment by TKone7** [comment]
I agree with the first part of your proposal, to count all requests except for some reasons (same user / IP within a certain time frame). 
I have doubts about the measure of "time spent" (TS). Since we are operating statelessly it is not trivial to figure out how long the user spent on the site reading. We only know when we delivered it, and when he requested some other page. But he could also just close the browser window (so he quit reading but we don't know for sure when) or open another page in a different tab (could look as he went to another page but might still be reading it somewhere else). Without sophisticated client side tracking code this approach is not feasible in my opinion. I, therefore, recommend to chose an approach that is viable statelessly.

**Comment by RomanBoegli** [comment]
done
